cidade(blumenau).
cidade(pelotas).
cidade(riogrande).
cidade(brusque).
cidade(florianopolis).
cidade(criciuma).
cidade(joinville).
cidade(indaial).
cidade(timbo).
cidade(taio).
cidade(fraiburgo).
cidade(itajai).
cidade(gaspar).
cidade(maua).
cidade(pomerode).
cidade(biguacu).
cidade(bombinhas).
cidade(camboriu).
cidade(itapema).
